name: everlink_lottery_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dartz: ^0.10.1
  firebase_auth: ^5.2.1
  firebase_core: ^3.4.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10+1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  get_it: ^7.7.0
  go_router: ^14.2.7
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  intl: any
  riverpod_annotation: ^2.3.5
  salomon_bottom_bar: ^3.3.2
  solar_icons: ^0.0.5

  image_picker: ^1.1.2
  firebase_storage: ^12.3.1
  provider: ^6.1.2
  cloud_firestore: ^5.4.2

  shared_preferences: ^2.3.2
  ionicons: ^0.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.5
  riverpod_lint: ^2.3.13

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/diningtable.jpg
    - assets/kitchencabinet.jpg
    - assets/sofa.jpeg
    - assets/TvStand.png

